// <auto-generated />
using System;
using Estudantes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estudantes.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estudantes.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Estudantes.Models.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Rio Branco",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Cruzeiro do Sul",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Sena Madureira",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Tarauacá",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Feijó",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Brasiléia",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Xapuri",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "8",
                            Name = "Epitaciolândia",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "9",
                            Name = "Plácido de Castro",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "10",
                            Name = "Porto Walter",
                            StateId = "AC"
                        },
                        new
                        {
                            Id = "11",
                            Name = "Maceió",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "12",
                            Name = "Arapiraca",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "13",
                            Name = "Palmeira dos Índios",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "14",
                            Name = "Rio Largo",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "15",
                            Name = "Penedo",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "16",
                            Name = "Delmiro Gouveia",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "17",
                            Name = "União dos Palmares",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "18",
                            Name = "Murici",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "19",
                            Name = "Coruripe",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "20",
                            Name = "Satuba",
                            StateId = "AL"
                        },
                        new
                        {
                            Id = "21",
                            Name = "Manaus",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "22",
                            Name = "Parintins",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "23",
                            Name = "Itacoatiara",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "24",
                            Name = "Manacapuru",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "25",
                            Name = "Coari",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "26",
                            Name = "Tabatinga",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "27",
                            Name = "Tefé",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "28",
                            Name = "Humaitá",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "29",
                            Name = "Boa Vista do Ramos",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "30",
                            Name = "Lábrea",
                            StateId = "AM"
                        },
                        new
                        {
                            Id = "31",
                            Name = "Salvador",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "32",
                            Name = "Feira de Santana",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "33",
                            Name = "Vitória da Conquista",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "34",
                            Name = "Camaçari",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "35",
                            Name = "Juazeiro",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "36",
                            Name = "Ilhéus",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "37",
                            Name = "Itabuna",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "38",
                            Name = "Lauro de Freitas",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "39",
                            Name = "Porto Seguro",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "40",
                            Name = "Teixeira de Freitas",
                            StateId = "BA"
                        },
                        new
                        {
                            Id = "41",
                            Name = "Fortaleza",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "42",
                            Name = "Juazeiro do Norte",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "43",
                            Name = "Caucaia",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "44",
                            Name = "Sobral",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "45",
                            Name = "Maracanaú",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "46",
                            Name = "Crato",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "47",
                            Name = "Aquiraz",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "48",
                            Name = "Iguatu",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "49",
                            Name = "São Gonçalo do Amarante",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "50",
                            Name = "Tianguá",
                            StateId = "CE"
                        },
                        new
                        {
                            Id = "51",
                            Name = "Vitória",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "52",
                            Name = "Vila Velha",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "53",
                            Name = "Serra",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "54",
                            Name = "Cariacica",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "55",
                            Name = "Guarapari",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "56",
                            Name = "Linhares",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "57",
                            Name = "Colatina",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "58",
                            Name = "Cachoeiro de Itapemirim",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "59",
                            Name = "São Mateus",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "60",
                            Name = "Nova Venécia",
                            StateId = "ES"
                        },
                        new
                        {
                            Id = "61",
                            Name = "Goiânia",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "62",
                            Name = "Aparecida de Goiânia",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "63",
                            Name = "Anápolis",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "64",
                            Name = "Rio Verde",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "65",
                            Name = "Luziânia",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "66",
                            Name = "Catalão",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "67",
                            Name = "Jataí",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "68",
                            Name = "Itumbiara",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "69",
                            Name = "Águas Lindas de Goiás",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "70",
                            Name = "Planaltina",
                            StateId = "GO"
                        },
                        new
                        {
                            Id = "71",
                            Name = "Brasília",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "72",
                            Name = "Gama",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "73",
                            Name = "Taguatinga",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "74",
                            Name = "Ceilândia",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "75",
                            Name = "Planaltina",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "76",
                            Name = "Águas Claras",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "77",
                            Name = "Samambaia",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "78",
                            Name = "Recanto das Emas",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "79",
                            Name = "Lago Sul",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "80",
                            Name = "Lago Norte",
                            StateId = "DF"
                        },
                        new
                        {
                            Id = "81",
                            Name = "São Luís",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "82",
                            Name = "Imperatriz",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "83",
                            Name = "Caxias",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "84",
                            Name = "Timon",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "85",
                            Name = "São José de Ribamar",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "86",
                            Name = "Codó",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "87",
                            Name = "Bacabal",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "88",
                            Name = "Açailândia",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "89",
                            Name = "Chapadinha",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "90",
                            Name = "Paço do Lumiar",
                            StateId = "MA"
                        },
                        new
                        {
                            Id = "91",
                            Name = "Cuiabá",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "92",
                            Name = "Várzea Grande",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "93",
                            Name = "Rondonópolis",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "94",
                            Name = "Sinop",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "95",
                            Name = "Lucas do Rio Verde",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "96",
                            Name = "Tangará da Serra",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "97",
                            Name = "Alta Floresta",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "98",
                            Name = "Sorriso",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "99",
                            Name = "Cáceres",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "100",
                            Name = "Barra do Garças",
                            StateId = "MT"
                        },
                        new
                        {
                            Id = "101",
                            Name = "Campo Grande",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "102",
                            Name = "Dourados",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "103",
                            Name = "Três Lagoas",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "104",
                            Name = "Ponta Porã",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "105",
                            Name = "Corumbá",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "106",
                            Name = "Naviraí",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "107",
                            Name = "Sidrolândia",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "108",
                            Name = "Aquidauana",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "109",
                            Name = "Coxim",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "110",
                            Name = "São Gabriel do Oeste",
                            StateId = "MS"
                        },
                        new
                        {
                            Id = "111",
                            Name = "Belo Horizonte",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "112",
                            Name = "Uberlândia",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "113",
                            Name = "Contagem",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "114",
                            Name = "Juiz de Fora",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "115",
                            Name = "Montes Claros",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "116",
                            Name = "Betim",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "117",
                            Name = "Muriaé",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "118",
                            Name = "Poços de Caldas",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "119",
                            Name = "Ipatinga",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "120",
                            Name = "Governador Valadares",
                            StateId = "MG"
                        },
                        new
                        {
                            Id = "121",
                            Name = "Belém",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "122",
                            Name = "Ananindeua",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "123",
                            Name = "Santarém",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "124",
                            Name = "Marabá",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "125",
                            Name = "Castanhal",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "126",
                            Name = "Parauapebas",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "127",
                            Name = "Tailândia",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "128",
                            Name = "Altamira",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "129",
                            Name = "Barcarena",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "130",
                            Name = "Breves",
                            StateId = "PA"
                        },
                        new
                        {
                            Id = "131",
                            Name = "João Pessoa",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "132",
                            Name = "Campina Grande",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "133",
                            Name = "Patos",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "134",
                            Name = "Cabedelo",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "135",
                            Name = "Santa Rita",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "136",
                            Name = "Bayeux",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "137",
                            Name = "Sousa",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "138",
                            Name = "Cajazeiras",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "139",
                            Name = "São Bento",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "140",
                            Name = "Monteiro",
                            StateId = "PB"
                        },
                        new
                        {
                            Id = "141",
                            Name = "Curitiba",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "142",
                            Name = "Londrina",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "143",
                            Name = "Maringá",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "144",
                            Name = "Ponta Grossa",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "145",
                            Name = "Cascavel",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "146",
                            Name = "Foz do Iguaçu",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "147",
                            Name = "Guarapuava",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "148",
                            Name = "São José dos Pinhais",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "149",
                            Name = "Paranaguá",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "150",
                            Name = "Araucária",
                            StateId = "PR"
                        },
                        new
                        {
                            Id = "151",
                            Name = "Recife",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "152",
                            Name = "Olinda",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "153",
                            Name = "Jaboatão dos Guararapes",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "154",
                            Name = "Caruaru",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "155",
                            Name = "Petrolina",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "156",
                            Name = "Cabo de Santo Agostinho",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "157",
                            Name = "Garanhuns",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "158",
                            Name = "Igarassu",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "159",
                            Name = "Afogados da Ingazeira",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "160",
                            Name = "Arcoverde",
                            StateId = "PE"
                        },
                        new
                        {
                            Id = "161",
                            Name = "Teresina",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "162",
                            Name = "Parnaíba",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "163",
                            Name = "Picos",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "164",
                            Name = "Campo Maior",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "165",
                            Name = "Floriano",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "166",
                            Name = "Barras",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "167",
                            Name = "São Raimundo Nonato",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "168",
                            Name = "Uruçuí",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "169",
                            Name = "Oeiras",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "170",
                            Name = "Barras",
                            StateId = "PI"
                        },
                        new
                        {
                            Id = "171",
                            Name = "Rio de Janeiro",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "172",
                            Name = "Niterói",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "173",
                            Name = "Nova Iguaçu",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "174",
                            Name = "São Gonçalo",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "175",
                            Name = "Duque de Caxias",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "176",
                            Name = "Volta Redonda",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "177",
                            Name = "Cabo Frio",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "178",
                            Name = "Macaé",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "179",
                            Name = "Belford Roxo",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "180",
                            Name = "Angra dos Reis",
                            StateId = "RJ"
                        },
                        new
                        {
                            Id = "181",
                            Name = "Natal",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "182",
                            Name = "Mossoró",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "183",
                            Name = "Parnamirim",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "184",
                            Name = "Caicó",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "185",
                            Name = "São Gonçalo do Amarante",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "186",
                            Name = "Açu",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "187",
                            Name = "Currais Novos",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "188",
                            Name = "Santa Cruz",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "189",
                            Name = "Pau dos Ferros",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "190",
                            Name = "João Câmara",
                            StateId = "RN"
                        },
                        new
                        {
                            Id = "191",
                            Name = "Porto Alegre",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "192",
                            Name = "Caxias do Sul",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "193",
                            Name = "Pelotas",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "194",
                            Name = "Santa Maria",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "195",
                            Name = "Viamão",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "196",
                            Name = "Gravataí",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "197",
                            Name = "Passo Fundo",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "198",
                            Name = "São Leopoldo",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "199",
                            Name = "Novo Hamburgo",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "200",
                            Name = "Rio Grande",
                            StateId = "RS"
                        },
                        new
                        {
                            Id = "201",
                            Name = "Porto Velho",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "202",
                            Name = "Ji-Paraná",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "203",
                            Name = "Ariquemes",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "204",
                            Name = "Cacoal",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "205",
                            Name = "Vilhena",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "206",
                            Name = "Rolim de Moura",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "207",
                            Name = "Ouro Preto do Oeste",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "208",
                            Name = "Guajará-Mirim",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "209",
                            Name = "São Francisco do Guaporé",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "210",
                            Name = "Nova Mamoré",
                            StateId = "RO"
                        },
                        new
                        {
                            Id = "211",
                            Name = "Boa Vista",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "212",
                            Name = "Rorainópolis",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "213",
                            Name = "Caracaraí",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "214",
                            Name = "Cantá",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "215",
                            Name = "Mucajaí",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "216",
                            Name = "Normandia",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "217",
                            Name = "São João da Baliza",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "218",
                            Name = "São Luiz",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "219",
                            Name = "Uiramutã",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "220",
                            Name = "Iracema",
                            StateId = "RR"
                        },
                        new
                        {
                            Id = "221",
                            Name = "Florianópolis",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "222",
                            Name = "Joinville",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "223",
                            Name = "Blumenau",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "224",
                            Name = "Chapecó",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "225",
                            Name = "São José",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "226",
                            Name = "Criciúma",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "227",
                            Name = "Lages",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "228",
                            Name = "Itajaí",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "229",
                            Name = "Ponta Grossa",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "230",
                            Name = "Tubarão",
                            StateId = "SC"
                        },
                        new
                        {
                            Id = "231",
                            Name = "São Paulo",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "232",
                            Name = "Campinas",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "233",
                            Name = "Guarulhos",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "234",
                            Name = "Santos",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "235",
                            Name = "São Bernardo do Campo",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "236",
                            Name = "Ribeirão Preto",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "237",
                            Name = "Sorocaba",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "238",
                            Name = "São José dos Campos",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "239",
                            Name = "Bauru",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "240",
                            Name = "Mogi das Cruzes",
                            StateId = "SP"
                        },
                        new
                        {
                            Id = "241",
                            Name = "Aracaju",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "242",
                            Name = "Nossa Senhora do Socorro",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "243",
                            Name = "Lagarto",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "244",
                            Name = "Itabaiana",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "245",
                            Name = "Propriá",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "246",
                            Name = "Estância",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "247",
                            Name = "Itabaianinha",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "248",
                            Name = "São Cristóvão",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "249",
                            Name = "Simão Dias",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "250",
                            Name = "Barra dos Coqueiros",
                            StateId = "SE"
                        },
                        new
                        {
                            Id = "251",
                            Name = "Palmas",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "252",
                            Name = "Araguaína",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "253",
                            Name = "Gurupi",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "254",
                            Name = "Porto Nacional",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "255",
                            Name = "Miracema do Tocantins",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "256",
                            Name = "Paraíso do Tocantins",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "257",
                            Name = "Tocantinópolis",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "258",
                            Name = "Dianópolis",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "259",
                            Name = "Augustinópolis",
                            StateId = "TO"
                        },
                        new
                        {
                            Id = "260",
                            Name = "Colinas do Tocantins",
                            StateId = "TO"
                        });
                });

            modelBuilder.Entity("Estudantes.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EducationalnstitutionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationalnstitutionId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Estudantes.Models.EducationalInstitution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationalInstitution");
                });

            modelBuilder.Entity("Estudantes.Models.State", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = "AC",
                            Name = "Acre"
                        },
                        new
                        {
                            Id = "AL",
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = "AM",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = "BA",
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = "CE",
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = "ES",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = "GO",
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = "MA",
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = "MT",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = "MS",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = "MG",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = "PA",
                            Name = "Pará"
                        },
                        new
                        {
                            Id = "PB",
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = "PR",
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = "PE",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = "PI",
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = "RJ",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = "RN",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = "RS",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = "RO",
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = "RR",
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = "SC",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = "SP",
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = "SE",
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = "TO",
                            Name = "Tocantins"
                        },
                        new
                        {
                            Id = "DF",
                            Name = "Distrito Federal"
                        });
                });

            modelBuilder.Entity("Estudantes.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Estudantes.Models.Address", b =>
                {
                    b.HasOne("Estudantes.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Estudantes.Models.City", b =>
                {
                    b.HasOne("Estudantes.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Estudantes.Models.Course", b =>
                {
                    b.HasOne("Estudantes.Models.EducationalInstitution", "Educationalnstitution")
                        .WithMany()
                        .HasForeignKey("EducationalnstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Educationalnstitution");
                });

            modelBuilder.Entity("Estudantes.Models.Student", b =>
                {
                    b.HasOne("Estudantes.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estudantes.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Estudantes.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
